### ISSUE TITLE
Code for mobile robot example

### ISSUE THREAD

**Issue by Yisten** [BolunDai0216/DifferentiableOptimizationCBF#1]
Thank you for your great work!

The open-sourced code currently seems not to include the experiments of mobile robot. It will be greatly appreciated to share the relevant code to reimplement Fig.3 in your paper!

Thank you. Looking forward to your reply!

**Comment by BolunDai0216** [comment]
@Yisten Thank you for your interest in our work!

Sure, I can dig it up and add it to the repo.

Also, if you are interested in mobile robot navigation using CBFs you can also take a look at our recent work: https://ieeexplore.ieee.org/document/10606004.

**Comment by BolunDai0216** [comment]
@Yisten see #2.

I will close this issue. If you have any further questions, please feel free to reopen it.

**Comment by Yisten** [comment]
got it! Thank you for your quick response
